import './assets/css/theme.min.css'
import './assets/css/globals.css'


export const metadata = {
  title: 'Aatmic Fit',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
